#
# Copyright 2011-2020 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

BGFX_DIR=../../
RUNTIME_DIR=$(BGFX_DIR)/../
BUILD_DIR=../../build

include ./../../common/shader.mk
