#
# Copyright 2011-2020 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

RUNTIME_DIR=./
BUILD_DIR=./../../../tools/Build

include ./Library/Base/shader.mk
